[theme]
# Primary accent for interactive elements
primaryColor="#F46524"

# Background color for the main content area
backgroundColor="#273346"

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor="#F46524"

# Color used for almost all text
textColor="#FFFFFF"

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font="sans serif"

[client]
showSidebarNavigation = false